image: java:8-jdk

stages:
  - install-dependencies
  - build
  - test
  - jar

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew


cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

install-dependencies:
  stage: install-dependencies
  script:
    - ./gradlew --refresh-dependencies

build:
  stage: build
  script: ./gradlew build
  cache:
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
  cache:
    paths:
      - build
      - .gradle
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

jar:
  stage: jar
  script: ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs